# Generated by Django 4.2.3 on 2023-07-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='desc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
